(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var j3=function(a){a.W("cardstatechange",a.gh()&&a.Lj()?1:0)},k3=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},YKa=function(a){var b=g.Kl(a);
a=g.Ql(a);return new g.rl(b.x,b.y,a.width,a.height)},ZKa=function(a){return Math.pow(a,3)},$Ka=function(a){return 3*a*a-2*a*a*a},n3=function(a){a=g.Qa(a);
delete l3[a];g.Ub(l3)&&m3&&m3.stop()},bLa=function(){m3||(m3=new g.J(function(){aLa()},20));
var a=m3;a.isActive()||a.start()},aLa=function(){var a=g.Ta();
g.Hb(l3,function(b){cLa(b,a)});
g.Ub(l3)||bLa()},o3=function(a,b,c,d){g.Tq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.u=null},cLa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.u);a.u=b;dLa(a,a.progress);1==a.progress?(a.Oa=0,n3(a),a.onFinish(),a.Vt()):a.tc()&&a.wz()},dLa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},eLa=function(a,b){g.kf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.Oa},p3=function(a,b,c,d,e){o3.call(this,b,c,d,e);
this.element=a},q3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
p3.call(this,a,b,c,d,e)},r3=function(a){g.E.call(this);
this.l=a||window;this.i=[]},s3=function(a){return a.baseUrl||null},t3=function(a,b){return g.ug(g.Ab(a,b,void 0),function(c){return!!c})},fLa=function(a,b,c){function d(Ba){var za,ed,Ze,oc=Ba.hovercardButton;
if(!oc)return null;oc=oc.subscribeButtonRenderer;if(!oc)return null;var De=f(oc.unsubscribedButtonText),Gd=f(oc.subscribedButtonText);if(oc.subscribed){var Kh=f(oc.subscriberCountWithUnsubscribeText);var Rg=f(oc.subscriberCountText)}else Kh=f(oc.subscriberCountText),Rg=f(oc.subscriberCountWithSubscribeText);var hc=null;return Ba.signinEndpoint&&(hc=k3(Ba,"signinEndpoint","webNavigationEndpointData","url"),hc||(hc=null===(Ze=null===(ed=null===(za=oc.signInEndpoint)||void 0===za?void 0:za.commandMetadata)||
void 0===ed?void 0:ed.webCommandMetadata)||void 0===Ze?void 0:Ze.url),!hc)?null:De&&(Gd||hc)?{subscribed:oc.subscribed,subscribeText:De,subscribeCount:Kh,unsubscribeText:Gd,unsubscribeCount:Rg,enabled:oc.enabled,signinUrl:hc,classic:Ba.useClassicSubscribeButton}:null}
function e(Ba){if(Ba){var za=[],ed=Ba.videoId;ed&&za.push("v="+ed);(ed=Ba.playlistId)&&za.push("list="+ed);(Ba=Ba.startTimeSeconds)&&za.push("t="+Ba);return"/watch?"+za.join("&")}}
function f(Ba){if(!Ba)return null;var za=Ba.simpleText;return za?za:Ba.runs?g.Ab(Ba.runs,function(ed){return ed.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,B=null,G=null,H=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=k3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):B=f(b.subscribersText)}else"WEBSITE"===
h?((G=k3(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=k3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=k3(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:null,L="";if(b.metadata){var fa=f(b.metadata);fa&&(L=fa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:L,callToAction:f(b.callToAction),
JG:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:B,isSubscribe:x,targetUrl:m||null,HP:n,Pd:M?{itct:M}:null,BU:p,Yr:a?a:null,KP:b.isPlaceholder,impressionUrls:t3(b.impressionUrls||[],s3),zP:t3(b.hovercardShowUrls||[],s3),clickUrls:t3(l.loggingUrls||[],s3),visualElement:g.Dx(b.trackingParams),
productPrice:H,additionalFeesText:I}},u3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:t3(a.impressionUrls||[],s3),elements:t3(a.elements||[],function(d,e){return fLa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Dx(a.trackingParams));return c},v3=function(a){g.IN.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.U=!0;this.G=0;a=a.T();this.K=g.nG(a)||g.rG(a);this.events=new g.xN(this);g.F(this,this.events);this.events.N(this.player,g.Jz("creatorendscreen"),this.zd);this.events.N(this.player,g.Kz("creatorendscreen"),this.Ze);this.events.N(this.player,"resize",this.tb);this.events.N(window,"focus",this.zT);this.load();var b=g.pg("STYLE");(g.bg("HEAD")[0]||document.body).appendChild(b);g.jf(this,function(){g.tg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},gLa=function(a){return a.player.getVideoData().C?"current":a.K?"new":"current"},w3=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},hLa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=u3(f,gLa(a))));x3(a,f)},
urlParams:{v:c},withCredentials:!0};a.K&&(c.urlParams.ptype="embedded");var d=b.Mn;d&&(c.postParams={ad_tracking:d});if(b=g.$ma(b))if(b=g.Mc(b),b=g.Ic(b))a.u=g.Rs(b,c)},x3=function(a,b,c){c=void 0===c?!0:c;
a.player.cf("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&iLa(a);c=[];d=new g.Gz(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.V({D:"div",L:"ytp-ce-shadow"}),g.vN(a.player,a.l.element,4),a.B=new g.mM(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=jLa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.vN(a.player,f.element,4);var h=new g.Gz(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);kLa(a,f,e)}else g.Vx(new g.Hv("buildEndscreenElement null",
e))}a.player.Dd(c);a.tb()}},iLa=function(a){var b=g.Hx(),c=g.Jx();
c&&b&&a.endscreen.visualElement&&g.Ry(c,b,a.endscreen.visualElement)},jLa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":b.Yr||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-covering-image",V:y3(b)},{D:"div",L:"ytp-ce-covering-shadow-top"},{D:"a",L:"ytp-ce-covering-overlay",V:{href:z3(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-video-title"].concat(g.ma(c)),V:{dir:g.Zq(b.title||
"")},oa:b.title},{D:"div",L:"ytp-ce-video-duration",oa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":b.Yr||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-covering-image",V:y3(b)},{D:"div",L:"ytp-ce-covering-shadow-top"},{D:"a",L:"ytp-ce-covering-overlay",V:{href:z3(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-playlist-title"].concat(g.ma(c)),V:{dir:g.Zq(b.title||"")},oa:b.title},{D:"div",L:"ytp-ce-playlist-count",S:[{D:"div",L:"ytp-ce-playlist-icon"},{D:"div",L:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":b.Yr||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},
{D:"div",L:"ytp-ce-expanding-overlay",S:[{D:"div",L:"ytp-ce-expanding-overlay-hider"},{D:"div",L:"ytp-ce-expanding-overlay-background"},{D:"div",L:"ytp-ce-expanding-overlay-content",S:[{D:"div",L:"ytp-ce-expanding-overlay-body",S:[{D:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ca:["ytp-ce-channel-title","ytp-ce-link"],V:{href:z3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Zq(b.title||"")},oa:b.title},b.subscribeButton?{D:"div",L:"ytp-ce-subscribe-container",S:[{D:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",L:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{D:"div",Ca:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{D:"div",L:"ytp-ce-expanding-image",V:y3(b)}]};c=new g.V(c);var d=g.cg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Pd.itct}else e="endscreen",f=null;e=new g.PO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ca:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":b.Yr||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-expanding-overlay",S:[{D:"div",L:"ytp-ce-expanding-overlay-hider"},
{D:"div",L:"ytp-ce-expanding-overlay-background"},{D:"div",L:"ytp-ce-expanding-overlay-content",S:[{D:"div",L:"ytp-ce-expanding-overlay-body",S:[{D:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",L:"ytp-ce-website-title",V:{dir:g.Zq(b.title||"")},oa:b.title},{D:"div",L:"ytp-ce-website-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-website-goto","ytp-ce-link"],V:{href:z3(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{D:"div",L:"ytp-ce-expanding-image",V:y3(b)},{D:"div",
L:"ytp-ce-expanding-icon",V:lLa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",L:"ytp-ce-merchandise-price-container",S:[{D:"div",L:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",L:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={D:"div",Ca:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":b.Yr||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-expanding-overlay",
S:[{D:"div",L:"ytp-ce-expanding-overlay-hider"},{D:"div",L:"ytp-ce-expanding-overlay-background"},{D:"div",L:"ytp-ce-expanding-overlay-content",S:[{D:"div",L:"ytp-ce-expanding-overlay-body",S:[{D:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",L:"ytp-ce-merchandise-title",V:{dir:g.Zq(b.title||"")},oa:b.title},c,{D:"div",L:"ytp-ce-merchandise-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:z3(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},
{D:"div",L:"ytp-ce-expanding-image",V:y3(b)},{D:"div",L:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",L:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.V(a)}b.KP&&g.K(c.element,"ytp-ce-placeholder");return c},y3=function(a){if(a.JG)var b=a.JG.thumbnails;
return lLa(b?b[b.length-1].url:null)},lLa=function(a){return a?{style:"background-image: url("+a+")"}:{}},kLa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.U&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.K(b.element,"ytp-ce-force-expand"),A3(a,c.id,!0)):(g.Qq(b.element,"ytp-ce-force-expand"),g.Qq(b.element,"ytp-ce-element-hover"),A3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){B3(a,b,c)});
b.Ra("mouseleave",function(){C3(a,b,c)});
a.player.T().i||b.Ra("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){mLa(a,c,m)});
b.Ra("keypress",function(m){mLa(a,c,m)});
b.Ra("focus",function(){B3(a,b,c)});
b.Ra("blur",function(){C3(a,b,c)});
b.Ra("touchstart",function(){B3(a,b,c)});
var l=g.eg("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Qq(b.element,"ytp-ce-element-hover");g.Qq(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.U=9===m.keyCode&&!m.shiftKey});
d(g.eg("ytp-sb-subscribe",b.element));d(g.eg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},mLa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Oq(d,"ytp-ce-element");){g.Oq(d,"subscribe-label")&&D3(a,b);
if(g.Oq(d,"ytp-ce-channel-subscribe"))return;d=g.vg(d)}if(!d||g.Oq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])C3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.BU)D3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Mc(z3(a,b.targetUrl)),c=g.Ic(c),g.nK(c,void 0,b.Pd);else{var e=a.player.getVideoData().C,f=function(){var h=z3(a,b.targetUrl),l=b.Pd,m=g.bs(h);e&&m&&(m.v||m.list)?a.player.nj(m.v,l,m.list,!1):g.mK(h,l)};
D3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},z3=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.RG(a)+b}else return"";return b},B3=function(a,b,c){g.Oq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),E3(a,c.zP),A3(a,c.id,!0))},C3=function(a,b,c){g.Qq(b.element,"ytp-ce-element-hover");
g.Qq(b.element,"ytp-ce-force-expand");A3(a,c.id,!1)},A3=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},E3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||w3(a))c&&c();else{b=nLa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.pu(b[a],d)}},D3=function(a,b,c){E3(a,b.clickUrls,c);
(a=g.Jx())&&b.HP&&g.Uy(a,b.visualElement)},nLa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(oLa(b[d],c));return a},oLa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},pLa=function(a){return Array.isArray(a)&&a.length?a[0]:a},F3=function(a){return"string"===typeof a?a:""},G3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},qLa=function(a){this.externalId=a},rLa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},H3=function(a){return a.value?a.value:null},I3=function(a){if(!a)return null;
var b=g.Mc(F3(a.value));b=g.Ic(b);if(!b)return null;var c=G3(a.target,sLa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new rLa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},tLa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},wLa=function(a){if(!a)return null;
var b=G3(a.type,uLa),c=G3(a.trigger,vLa),d=pLa(a.url);d=I3(d?d:null);a=pLa(a.subscribeData);var e=a?a:null;e?(a=F3(e.external_user_id),e=F3(e.subscription_token),a=a&&e?new qLa(a):null):a=null;return b?new tLa(b,c,d,a):null},xLa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},zLa=function(a){return(a=yLa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},yLa=function(a,b){return g.$a(a.action,b,void 0)},ALa=function(a,b){this.context=a;
this.i=b},K3=function(a){return a.customMessage?J3("div","iv-card-message",a.customMessage):""},L3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",L:"iv-card-image",V:{style:a},S:c}},M3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(J3("li","",c.value));return{D:"ul",L:"iv-card-meta-info",S:b}},J3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Zq(c);return{D:a,V:b,oa:c}},BLa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Iv&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Iv+");");c.dir=g.Zq(a.customMessage);var d=[{D:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",L:"iv-card-link-icon"}));return{D:"div",Ca:b,V:c,S:d}},N3=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Pd,c.tracking.click,5)}},CLa=function(a,b){this.merchant=a;
this.price=b},DLa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ELa=function(a,b){return b?b:DLa(a)?"current":"new"},O3=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.Wa=!1;this.Ga=new Map;this.Ma=new Map;this.context.I.addEventListener(g.Jz("annotations_module"),function(d){(d=c.Ga.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.Kz("annotations_module"),function(d){(d=c.Ma.get(d))&&d.apply(c)})},P3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.xz(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.Wa=!1});
a.context.i.Ra(b,"touchmove",function(){a.Wa=!0})},FLa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Q3=function(a,b,c){return{FH:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
AK:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sy:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},T3=function(a,b,c){O3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ea=this.eb=this.u=this.Td=!1;this.ma=null;this.cards=[];this.Ya=this.K=this.Aa=this.C=this.Da=this.i=null;this.Y=[];this.J=this.ge=this.xa=null;this.G=0;this.va=new g.J(g.Ja,c.B.Ac?4E3:3E3);g.F(this,this.va);this.Va=new g.J(g.Ja);g.F(this,this.Va);this.X=new ALa(c,function(e,f,h,l,m,n){P3(d,e,f,h,l,m,n)});
this.U=new g.V({D:"div",L:"iv-drawer",V:{id:"iv-drawer"},S:[{D:"div",L:"iv-drawer-header",V:{"aria-role":"heading"},S:[{D:"span",L:"iv-drawer-header-text"},{D:"button",Ca:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{D:"div",L:"iv-drawer-content"}]});g.F(this,this.U);this.B=this.U.element;this.Qa=new g.mM(this.U,330);g.F(this,this.Qa);this.bb=g.eg("iv-drawer-header-text",this.B);this.l=g.eg("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.eb&&R3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.eb=d.u)&&S3(d)})},GLa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){R3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){S3(a)});
var c=b.headerText;g.xg(a.bb,c);a.K&&a.K.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.xa=g.Dx(b.trackingParams);a.J=g.Dx(b.closeTrackingParams);a.ge=g.Dx(b.iconTrackingParams)},HLa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"simple",teaserText:g.Qz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Pd:U3(a,c,b,d),sponsored:!1,tracking:Q3(d,e,d.command),Sk:d.trackingParams?g.Dx(d.trackingParams):null,xi:e.trackingParams?
g.Dx(e.trackingParams):null,ge:f&&f.trackingParams?g.Dx(f.trackingParams):null,imageUrl:V3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Qz(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Iv:null,title:d.title?g.Qz(d.title):"",customMessage:d.callToAction?g.Qz(d.callToAction):"",url:d.command.urlEndpoint.url?I3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};W3(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"collaborator",teaserText:g.Qz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Pd:U3(a,c,b,d),sponsored:!1,tracking:Q3(d,e,d.endpoint),Sk:d.trackingParams?g.Dx(d.trackingParams):null,xi:e.trackingParams?g.Dx(e.trackingParams):null,ge:f&&f.trackingParams?g.Dx(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Qz(d.customText):null,profileImageUrl:V3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Qz(d.channelName):"",metaInfo:[d.subscriberCountText?g.Qz(d.subscriberCountText):""],url:I3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};W3(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"playlist",teaserText:g.Qz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Pd:U3(a,c,b,d),sponsored:!1,tracking:Q3(d,e,d.action),Sk:d.trackingParams?g.Dx(d.trackingParams):null,xi:e.trackingParams?g.Dx(e.trackingParams):null,ge:f&&f.trackingParams?g.Dx(f.trackingParams):
null,Ru:V3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Qz(d.customMessage):null,playlistVideoCount:g.Qz(d.playlistVideoCount),title:d.playlistTitle?g.Qz(d.playlistTitle):"",metaInfo:[d.channelName?g.Qz(d.channelName):"",d.videoCountText?g.Qz(d.videoCountText):""],url:I3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:FLa(d.action)})};W3(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"video",teaserText:g.Qz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Pd:U3(a,c,b,d),sponsored:!1,tracking:Q3(d,e,d.action),Sk:d.trackingParams?g.Dx(d.trackingParams):null,xi:e.trackingParams?g.Dx(e.trackingParams):null,ge:f&&f.trackingParams?g.Dx(f.trackingParams):null,Ru:V3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.Qz(d.lengthString):null,customMessage:d.customMessage?g.Qz(d.customMessage):null,title:d.videoTitle?g.Qz(d.videoTitle):"",metaInfo:[d.channelName?g.Qz(d.channelName):"",d.viewCountText?g.Qz(d.viewCountText):""],isLiveNow:!!d.badge,url:I3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:FLa(d.action)})};W3(a,b)}a.G++},V3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},U3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},JLa=function(a,b){if(b=ILa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.tg(b.tA),g.gb(a.cards,b),a.Kv(),X3(a)},R3=function(a,b,c){if(!a.u){a.Qa.show();
a.Da=new g.J(function(){g.K(a.context.I.getRootNode(),g.XT.IV_DRAWER_OPEN)},0);
a.Da.start();a.ma=g.Pt(a.l,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.Jx();d&&a.xa&&a.J&&g.Sy(d,[a.xa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.lI||(f.lI=!0,KLa(a.context.logger,f.card.tracking.FH,b)),d&&g.Sy(d,[f.card.Sk]);j3(a.I);c&&(a.C=new g.J(function(){a.Aa=a.K;a.Ya.focus()},330),a.C.start())}},S3=function(a){a.u&&(a.Qa.hide(),g.Qt(a.ma),a.ma=null,g.Qq(a.context.I.getRootNode(),g.XT.IV_DRAWER_OPEN),a.u=!1,j3(a.I),a.C&&a.C.stop(),a.C=new g.J(function(){a.Aa&&(a.Aa.focus(),a.Aa=null)},330),a.C.start())},
MLa=function(a){g.Pq(a.element,[g.XT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.vN(a.I,a.B,5);LLa(a);a.K=g.eg("ytp-cards-button",a.I.getRootNode());a.Ya=g.eg("iv-drawer-close-button",a.B);a.Td=!0},LLa=function(a){var b=g.eg("iv-drawer-close-button",a.B);
a.context.i.Ra(b,"click",a.kO,a);a.context.i.Ra(a.l,"touchend",function(){a.va.start()});
a.context.i.Ra(a.l,"scroll",a.wO,a);a.context.l.subscribe("onHideControls",function(){a.Ea=!0});
a.context.l.subscribe("onShowControls",function(){a.Ea=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Ea=g.Oq(a.I.getRootNode(),"ytp-autohide")});
a.Y.push(g.xu("iv-button-shown",a.SP,a));a.Y.push(g.xu("iv-button-hidden",a.RP,a));a.Y.push(g.xu("iv-teaser-shown",a.IM,a));a.Y.push(g.xu("iv-teaser-hidden",a.UP,a));a.Y.push(g.xu("iv-teaser-clicked",a.HM,a))},W3=function(a,b){a.Td||MLa(a);
JLa(a,b.id);var c=NLa(a,b);if(c){var d={card:b,tA:c.element,lI:!1},e=OLa(a,d);g.ob(a.cards,e,0,d);c.ya(a.l,e);a.Kv();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,X3(a),PLa(a,d),R3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&QLa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){QLa(a,d)}),X3(a))}},NLa=function(a,b){switch(b.type){case "simple":a=a.X;
var c=b.displayDomain?{D:"div",L:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=BLa(b);c={D:"div",Ca:["iv-card"],S:[{D:"a",L:"iv-click-target",V:{href:b.url?H3(b.url)||"":""},S:[L3(b.imageUrl,c),{D:"div",L:"iv-card-content",S:[J3("h2",void 0,b.title),d]}]}]};c=new g.V(c);N3(a,g.dg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.X,c={D:"div",Ca:["iv-card","iv-card-channel"],S:[{D:"a",Ca:["iv-click-target"],V:{href:H3(b.url)||"","data-ytid":b.channelId},S:[L3(b.profileImageUrl),
{D:"div",L:"iv-card-content",S:[K3(b),{D:"h2",L:"iv-card-primary-link",oa:b.title},M3(b)]}]}]},c=new g.V(c),N3(a,g.dg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.X,c={D:"div",Ca:["iv-card","iv-card-playlist"],S:[{D:"a",L:"iv-click-target",V:{href:H3(b.url)||""},S:[L3(b.Ru,{D:"div",L:"iv-card-image-overlay",S:[{D:"span",L:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{D:"div",L:"iv-card-content",S:[K3(b),J3("h2","iv-card-primary-link",b.title),M3(b)]}]}]},c=new g.V(c),
N3(a,g.dg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.X;var e=!g.db(b.offers);c=["iv-card"];d="";var f=BLa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",L:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({D:"div",L:"iv-card-offer-merchant",oa:f.merchant}),f={D:"div",S:e});e=b.url?H3(b.url)||"":"";c={D:"div",Ca:c,V:{tabindex:"0"},S:[{D:"a",Ca:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",L:"iv-card-content",S:[b.sponsored?{D:"div",L:"iv-card-sponsored",S:["Patrocinado",{D:"div",L:"iv-ad-info-container",S:[{D:"div",L:"iv-ad-info",oa:"{{adInfo}}"},{D:"div",L:"iv-ad-info-icon-container",S:[{D:"div",L:"iv-ad-info-icon"},{D:"div",L:"iv-ad-info-callout"}]}]}]}:"",{D:"a",L:"iv-click-target",V:{href:e},S:[J3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.pg("span");g.xg(d,"Ves este producto porque consideramos que es importante para el video. Es posible que Google reciba compensaciones del comerciante.");
c.Vc(d,"adInfo");N3(a,g.dg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.X,d=b.videoDuration?{D:"span",L:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ca:["yt-badge","yt-badge-live"],oa:"EN DIRECTO AHORA"}:null,d={D:"div",Ca:["iv-card","iv-card-video"],S:[{D:"a",L:"iv-click-target",V:{href:(null===(c=b.url)||void 0===c?void 0:H3(c))||""},S:[L3(b.Ru,d),{D:"div",L:"iv-card-content",S:[K3(b),J3("h2","iv-card-primary-link",b.title),M3(b),f]}]}]},
c=new g.V(d),N3(a,g.dg("iv-click-target",c.element),b,b.url),c;default:return null}},OLa=function(a,b){if(0===a.cards.length)return 0;
a=g.ab(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},RLa=function(a){return a.i?"productListing"===a.i.card.type:g.Bm(a.cards,function(b){return"productListing"===b.card.type})},X3=function(a){g.N(a.I.getRootNode(),"ytp-cards-shopping-active",RLa(a))},QLa=function(a,b){if(!g.Oq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Jx(),d=a.i?a.i.card.ge:a.ge;
c&&d&&g.Ty(c,[d]);a.i=b;X3(a)}if(c="none"!=a.element.style.display)g.S(a.context.I.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Zq(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Va.isActive()||((!a.u||!a.va.isActive()&&a.Ea)&&PLa(a,b),a.Va.start(910+b.card.teaserDurationMs))}},
PLa=function(a,b){a.U.vb?(b=new o3([0,
a.l.scrollTop],[0,b.tA.offsetTop],600,$Ka),a.context.u.Ra(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Ra(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.DL(a.U,!0),a.l.scrollTop=b.tA.offsetTop,g.DL(a.U,!1))},Y3=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},ILa=function(a,b){return g.$a(a.cards,function(c){return c.card.id===b})},Z3=function(a,b,c){O3.call(this,a,b);
this.annotation=c;this.isActive=!1},SLa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},$3=function(a,b,c){Z3.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},TLa=function(a,b){var c=void 0===c?0:c;
var d=YKa(b).width;g.Il(b,d);c=new q3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,ZKa);g.F(a,c);a.context.u.Ra(c,"begin",function(){g.Rl(b,!0)});
c.play()},WLa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ca:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({D:"div",Ca:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.PO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.I),a.i.ya(d));var f=a.createElement({D:"div",Ca:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ca:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Rl(h,!1);var l=a.createElement({D:"div",Ca:["branding-context-container-outer"]});l.appendChild(h);g.Bl(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){ULa(a,h,l)},500);
g.F(a,a.u);a.context.i.Ra(a.element,"mouseover",function(){VLa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.u.start()})}},VLa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Ql(b);a.i||(b.style.width=g.Hl(f.width,!0),c.style.width=g.Hl(f.width,!0));g.Bl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Bl(d,"right","1px");a.B=!0;g.Rl(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},ULa=function(a,b,c){g.Qq(a.element,"iv-branding-active");
a.G=new g.J(function(){g.Rl(b,!1);a.i||(c.style.width=g.Hl(0,!0))},250);
a.G.start();a.B=!1},XLa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.I=f;this.l=h},a4=function(a,b,c){Z3.call(this,a,b,c);
var d=this;this.K=this.isCollapsed=this.U=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ca:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Rl(d.u,!1);g.Rl(d.l,!0)},700,this);
g.F(this,this.C)},YLa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promoci\u00f3n");a.element.tabIndex=0;var e=zLa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ca:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",V:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",L:"iv-promo-video-duration",oa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",L:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),h.appendChild(f));e&&P3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",L:"iv-promo-txt"}),g.nd(f,H3(e)),a.i=f):a.i=a.createElement({D:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
oa:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",L:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ca:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ca:["iv-button","iv-promo-button"],S:[{D:"span",L:"iv-button-content",oa:f}]});var p=a.createElement({D:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&P3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&P3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",oa:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ca:["yt-badge","iv-promo-badge-live"],oa:"EN DIRECTO AHORA"})),g.K(a.i,"iv-click-target"),e&&P3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);
p&&a.J.appendChild(p);c=a.createElement({D:"div",L:"iv-promo-actions"});a.l=a.createElement({D:"button",Ca:["iv-promo-expand","ytp-button"]});a.l.title="Expandir";a.context.i.Ra(a.l,"click",function(r){b4(a,5E3,r)});
c.appendChild(a.l);g.Rl(a.l,!1);a.context.i.Ra(a.element,"mouseover",a.dP,a);a.context.i.Ra(a.element,"mouseout",a.cP,a);a.context.i.Ra(a.element,"touchend",function(r){b4(a,5E3,r)});
a.u=a.createElement({D:"button",Ca:["iv-promo-close","ytp-button"]});a.u.title="Cerrar";a.context.i.Ra(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.YO:a.XO,a);c.appendChild(a.u);g.Pq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},b4=function(a,b,c){c.stopPropagation();
ZLa(a);$La(a,b);a.i.focus()},aMa=function(a){a.isCollapsed||a.K||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},ZLa=function(a){a.C.stop();
a.isCollapsed&&(g.Rq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Rl(a.l,!1),g.Rl(a.u,!0))},$La=function(a,b){a.B||(a.B=g.mh(function(){c4(this);
aMa(this)},b,a))},c4=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},bMa=function(a){this.I=a},KLa=function(a,b,c){b&&(c?d4(a,b.map(function(d){return g.Aq(d,c)})):d4(a,b))},d4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.pu(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},e4=function(a){g.IN.call(this,a);
var b=this;this.U=!1;this.loadNumber=0;this.J={};this.logger=new bMa(this.player);this.C=new g.xN(this);this.G=this.u=null;this.events=new g.xN(this);this.K=this.i=null;this.Y=[];g.F(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.W("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.W("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.W("onShowControls")});
this.C.N(this.player,"resize",function(d){b.W("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.W("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.JM,this);this.subscribe("resize",this.Dx,this);this.player.T().U.subscribe("vast_info_card_add",this.BJ,this);g.F(this,this.events);this.X=this.createElement({D:"div",L:"video-custom-annotations"});this.l=new g.V({D:"div",Ca:["ytp-player-content","ytp-iv-player-content"]});g.F(this,this.l);g.vN(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Ca:["ytp-iv-video-content"]});g.F(this,this.B);a=this.createElement({D:"div",L:"video-annotations"});
a.appendChild(this.X);this.B.element.appendChild(a);this.zp()&&this.load();var c=this.createElement({D:"style"});(g.bg("HEAD")[0]||document.body).appendChild(c);g.jf(this,function(){g.tg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},cMa=function(a){a=a.createElement({D:"div",
Ca:["annotation","annotation-type-custom"]});g.Rl(a,!1);return a},dMa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.DL(a.l,b);g.DL(a.B,b)},eMa=function(a,b,c){a.U=!0;
a.G=g.Rs(b,c)},fMa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(fMa(a,e))}return c},iMa=function(a){var b=a.player.getVideoData();
if(b.xa){var c=a.player.T().U.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.ns(h)&&h.responseXML?h.responseXML:null)&&f4(a,h)}};
g.gu()&&(d.onFinish=gMa(a,d.onFinish));d.postParams={ic_only:"1"};hMa(d,c);a.U=!0;g.Rs(b.xa,d)}}},hMa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.ys&&(a.postParams.ic_coll=b.ys);b.Ov&&(a.postParams.ic_xml=b.Ov);b.Uu&&(a.postParams.ic_track=b.Uu)},jMa=function(a){var b=new g.V({D:"div"});
g.Rl(b.element,!1);var c=new T3(a.player,b.element,g4(a));g.F(c,b);b.ya(a.l.element);c.Du();return c},g4=function(a){if(!a.K){var b=new r3(a);
g.F(a,b);var c=new g.xk(a);g.F(a,c);a.K=new XLa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.cd)}return a.K},f4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Jx();if(e){var f=g.Hx();f&&g.by(g.Pr("use_default_events_client")?void 0:g.dx,e,f,[g.Dx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=fMa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=G3(f.type,kMa),p=G3(f.style,lMa),r=F3(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=wLa;if(null==u)var x=null;else if(g.Na(u)){l=[];for(var y=g.q(u),B=y.next();!B.done;B=
y.next()){var G=f(B.value);G&&l.push(G)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new xLa(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=cMa(f),M=null;switch(l.type){case "branding":if(f.player.T().wb)break;f.l.element.appendChild(I);M=new $3(I,g4(f),l);break;case "promotion":g.vN(f.player,I,4),M=new a4(I,g4(f),l)}M&&M.Du();if(f=M)g.F(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=jMa(a),g.F(a,a.i));if("card"===e.type){c=
a.i;var L=e&&e.data&&e.data.card_type;f=e.data;if(L)switch(l=f.tracking||{},l={FH:l.impression,click:l.click,close:l.close,AK:l.teaser_impression,sy:l.teaser_click},I=f.tracking_params||{},M=null,L){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Pd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Sk:I.card?g.Dx(I.card):null,xi:I.teaser?g.Dx(I.teaser):null,ge:I.icon?
g.Dx(I.icon):null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:I3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};W3(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Pd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Sk:I.card?
g.Dx(I.card):null,xi:I.teaser?g.Dx(I.teaser):null,ge:I.icon?g.Dx(I.icon):null,Ru:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:I3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};W3(c,e);break;case "productListing":f.signin_url&&(M=I3({target:"current",value:f.signin_url}));L=[];for(var fa=f.offers||[],Ba=0;Ba<fa.length;Ba++)L.push(new CLa(g.ud(fa[Ba].merchant),g.ud(fa[Ba].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Pd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Sk:I.card?g.Dx(I.card):null,xi:I.teaser?g.Dx(I.teaser):null,ge:I.icon?g.Dx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Iv:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:I3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),g8:M,f8:f.signin_title?f.signin_title:void 0,e8:f.signin_message?f.signin_message:void 0,offers:L};W3(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Pd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Sk:I.card?g.Dx(I.card):null,xi:I.teaser?g.Dx(I.teaser):
null,ge:I.icon?g.Dx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Iv:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:I3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};W3(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,Pd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Sk:I.card?g.Dx(I.card):null,xi:I.teaser?g.Dx(I.teaser):null,ge:I.icon?g.Dx(I.icon):null,Ru:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:I3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},W3(c,e)}}else GLa(a.i,e);c=!0}}c&&(j3(a.player),a.Dx())},mMa=function(a,b){var c=!1;
a.i||(a.i=jMa(a),g.F(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(HLa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.Qz(b.headerText):"",g.xg(c.bb,d),c.K&&c.K.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.xa=b.trackingParams?g.Dx(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Dx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.ge=b.icon.infoCardIconRenderer.trackingParams?
g.Dx(b.icon.infoCardIconRenderer.trackingParams):null,j3(a.player),a.Dx())},nMa=function(a,b,c,d,e){if(!a.player.T().wb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new tLa("openUrl","click",new rLa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Qz(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Qz(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Qz(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Qz(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.Qz(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Qz(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new xLa(c,"branding","branding",f,d);l=cMa(a);a.l.element.appendChild(l);f=new $3(l,g4(a),f);f.Du();g.F(f,f);a.J[c]=f}},gMa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.Ha()||a.Y.push(g.du(function(){b.apply(null,g.ma(d))}))}},oMa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.oN.prototype.Zq=g.ca(17,function(a,b){var c=g.ZN(this.rb());c&&c.Zq(a,b)});
var l3={},m3=null;g.Ua(o3,g.Tq);g.k=o3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Oa)this.progress=0,this.coords=this.i;else if(this.tc())return!1;n3(this);this.startTime=a=g.Ta();-1==this.Oa&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.u=this.startTime;this.progress||this.Bx();this.Nh("play");-1==this.Oa&&this.Nh("resume");this.Oa=1;var b=g.Qa(this);b in l3||(l3[b]=this);bLa();cLa(this,a);return!0};
g.k.stop=function(a){n3(this);this.Oa=0;a&&(this.progress=1);dLa(this,this.progress);this.Nh("stop");this.Vt()};
g.k.pause=function(){this.tc()&&(n3(this),this.Oa=-1,this.Nh("pause"))};
g.k.ra=function(){0==this.Oa||this.stop(!1);this.Nh("destroy");o3.Qd.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.wz=function(){this.Nh("animate")};
g.k.Nh=function(a){this.dispatchEvent(new eLa(a,this))};
g.Ua(eLa,g.kf);g.Ua(p3,o3);p3.prototype.l=g.Ja;p3.prototype.wz=function(){this.l();p3.Qd.wz.call(this)};
p3.prototype.Vt=function(){this.l();p3.Qd.Vt.call(this)};
p3.prototype.Bx=function(){this.l();p3.Qd.Bx.call(this)};
g.Ua(q3,p3);q3.prototype.l=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(r3,g.E);r3.prototype.Ra=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.Pt(a,b,c);this.i.push(a);return a};
r3.prototype.bx=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.Yt(a,b,c);this.i.push(a);return a};
r3.prototype.fc=function(a){g.Qt(a);g.gb(this.i,a)};
r3.prototype.ra=function(){g.Qt(this.i);this.i.length=0;g.E.prototype.ra.call(this)};g.v(v3,g.IN);g.k=v3.prototype;g.k.load=function(){g.IN.prototype.load.call(this);if(!w3(this)){var a=g.ana(this.player.getVideoData());a?(a=u3(a,gLa(this)),x3(this,a,!1)):hLa(this)}};
g.k.unload=function(){x3(this,null);this.u&&(this.u.abort(),this.u=null);g.IN.prototype.unload.call(this)};
g.k.Qe=function(a,b){return w3(this)?"loadCustomEndscreenRenderer"===a?(a=u3(b,"new"),x3(this,a),!0):null:null};
g.k.getOptions=function(){return w3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.tb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<pMa.length;f++){var h=Math.abs(b.width-pMa[f]);if(-1===e||d>=h)e=f,d=h}d=qMa[e];this.l&&g.Bl(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Pl(e.element,Math.round(h.width*a.width),f);g.Il(e.element,m,n);g.Rq(e.element,rMa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Rq(e.element,qMa);g.K(e.element,d);(e=g.cg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Bl(e,"height",f+"px")}}}}};
g.k.zd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())E3(this,this.endscreen.impressionUrls),(a=g.Jx())&&this.endscreen.visualElement&&g.cy(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");E3(this,c.impressionUrls);(b=g.Jx())&&g.cy(b,c.visualElement,void 0);this.player.T().u&&this.player.Na("endscreenelementshown",
a)}};
g.k.Ze=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Qq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Qq(b,"ytp-ce-shown");this.player.T().u&&this.player.Na("endscreenelementhidden",a)}};
g.k.zT=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Rq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var pMa=[346,426,470,506,570,640,853,1280,1920],qMa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),rMa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var sLa={CY:"current",g3:"new"};var uLa={CLOSE:"close",A3:"openUrl",MN:"subscribe"},vLa={uW:"click",CLOSE:"close",PZ:"hidden",J4:"rollOut",K4:"rollOver",w5:"shown"};var lMa={OV:"anchored",jL:"branding",CHANNEL:"channel",AY:"cta",SZ:"highlightText",O_:"label",PLAYLIST:"playlist",h4:"popup",E5:"speech",MN:"subscribe",V5:"title",VIDEO:"video",d7:"website"},kMa={jL:"branding",hW:"card",PY:"drawer",RZ:"highlight",x1:"marker",p4:"promotion",TEXT:"text",j7:"widget"};g.v(O3,g.E);g.k=O3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Gz(a,b,{id:c});a.namespace="annotations_module";d&&this.Ga.set(a,d);e&&this.Ma.set(a,e);this.context.I.Dd([a])};
g.k.Du=function(){this.context.l.subscribe("resize",this.Kv,this)};
g.k.xz=function(a,b,c,d,e,f){if(this.Wa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.tg(this.element)};
g.k.Kv=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=H3(a);if(f){var h=ELa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.C||!1,n=g.bs(f||"");m&&n&&(n.v||n.list)?e.context.I.nj(n.v,b,n.list,!1):g.nK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);d4(this.context.logger,c,l,d);DLa(f)||(c=g.Jx(),d=b.itct,c&&d&&g.Uy(c,g.Dx(d)))}};
g.k.ra=function(){this.Ga.clear();this.Ma.clear();g.E.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.v(T3,O3);g.k=T3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Ql(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Kv=function(){var a=this.isAvailable();g.Rl(this.element,a);g.N(this.context.I.getRootNode(),g.XT.IV_DRAWER_ENABLED,a);j3(this.I)};
g.k.destroy=function(){this.I.Zq(!1);try{this.I.getRootNode().removeChild(this.B)}catch(a){}g.yu(this.Y);g.Qt(this.ma);this.Da&&this.Da.dispose();this.C&&this.C.dispose();O3.prototype.destroy.call(this)};
g.k.kO=function(){if(this.u){d4(this.context.logger,Y3(this).tracking.close);var a=g.Jx();a&&this.J&&g.Uy(a,this.J);S3(this)}};
g.k.wO=function(){g.N(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.SP=function(){var a=g.Jx(),b=Y3(this);b=b?b.ge:this.ge;a&&b&&g.Sy(a,[b])};
g.k.RP=function(){var a=g.Jx(),b=Y3(this);b=b?b.ge:this.ge;a&&b&&g.Ty(a,[b])};
g.k.IM=function(){var a=Y3(this);d4(this.context.logger,a.tracking.AK);var b=g.Jx();b&&a&&g.Sy(b,[a.xi,a.ge])};
g.k.UP=function(){var a=g.Jx(),b=Y3(this);a&&b&&g.Ty(a,[b.xi])};
g.k.HM=function(a){var b=Y3(this),c=g.Jx();this.i?a?(a=this.context.logger,d4(a,b.tracking.sy),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.xi&&g.Uy(c,b.xi)):(a=this.context.logger,d4(a,b.tracking.sy),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.ge&&g.Uy(c,b.ge)):(a=this.context.logger,d4(a,b.tracking.sy),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.ge&&g.Uy(c,this.ge))};g.v(Z3,O3);Z3.prototype.Du=function(){O3.prototype.Du.call(this);SLa(this)};
Z3.prototype.show=function(){O3.prototype.show.call(this);var a=g.Jx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Sy(a,[g.Dx(b.itct)])};
Z3.prototype.hide=function(){O3.prototype.hide.call(this);var a=g.Jx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ty(a,[g.Dx(b.itct)])};g.v($3,Z3);
$3.prototype.show=function(){if(!this.isActive){Z3.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ca:["branding-img","iv-click-target"],V:{"aria-label":"Marca de agua del canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.Rl(this.l,!1);var b=this.createElement({D:"div",Ca:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=zLa(this.annotation))&&P3(this,this.l,b,this.annotation.id,
a.session_data);WLa(this,a);this.J=!0}g.Rl(this.element,!0);this.isActive=!0;this.l&&TLa(this,this.l)}};
$3.prototype.hide=function(){this.isActive&&(Z3.prototype.hide.call(this),g.Rl(this.element,!1),this.isActive=!1)};
$3.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);Z3.prototype.destroy.call(this)};g.v(a4,Z3);g.k=a4.prototype;g.k.show=function(){this.isActive||(Z3.prototype.show.call(this),this.U||(YLa(this),this.U=!0),g.Rl(this.element,!0),g.mh(function(){g.Qq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,c4(this),ZLa(this),$La(this,this.G))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.xz=function(a,b,c,d,e,f){return this.isCollapsed?!1:Z3.prototype.xz.call(this,a,b,c,d,e,f)};
g.k.dP=function(a){this.K=!0;b4(this,500,a)};
g.k.cP=function(){this.K=!1;aMa(this)};
g.k.XO=function(a){a.stopPropagation();this.hide()};
g.k.YO=function(a){a.stopPropagation();c4(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();Z3.prototype.destroy.call(this)};g.v(e4,g.IN);g.k=e4.prototype;g.k.Qe=function(a,b){if(!oMa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.T1(b))&&f4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(JLa(this.i,b),j3(this.player)),!0}return null};
g.k.getOptions=function(){return oMa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.zp=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.bG||a.U.get(b.videoId)||g.ZH(b)||g.$H(b)?!0:!1};
g.k.Dx=function(){if(this.B){var a=this.player.Za().getVideoContentRect(!0);g.Pl(this.B.element,a.width,a.height);g.Il(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Li();a=this.i;b=b.width;g.N(a.B,"iv-drawer-small",426>=b);g.N(a.B,"iv-drawer-big",1280<=b)}};
g.k.JM=function(a){dMa(this,a.state);g.U(a.state,2)&&(this.gh()&&this.Lj()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Zq(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.ns(h)&&h.responseXML?h.responseXML:null)&&(f4(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.IN.prototype.load.call(this);dMa(this,this.player.sb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.gu()&&(a=gMa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().U.get(d);f&&hMa(e,f);f=f&&(f.Ov||f.ys);if(!c.Lk||f)c.xa?eMa(this,c.xa,e):(this.u=function(){b.jb(e)},this.player.addEventListener("videodatachange",this.u));
g.vN(this.player,this.B.element,4);this.Dx();(f=g.ZH(c))&&mMa(this,f);(f=g.$H(c))&&f.featuredChannel&&nMa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.jb=function(a){var b=this.player.getVideoData();b.xa&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),eMa(this,b.xa,a))};
g.k.unload=function(){this.player.cf("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,j3(this.player));this.U=!1;this.G&&(this.G.abort(),this.G=null);this.J={};this.l.hide();g.IN.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.BJ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?iMa(this):this.load())};
g.k.gh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Lj=function(){this.gh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.gh();this.i&&(a?c?R3(this.i,c,b):R3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):S3(this.i))};
g.k.Zq=function(a,b){this.player.W(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.T().U.unsubscribe("vast_info_card_add",this.BJ,this);g.Qq(this.player.getRootNode(),g.XT.IV_DRAWER_OPEN);for(var a=this.Y,b=0,c=a.length;b<c;b++)g.hu(a[b]);this.Y.length=0;g.IN.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.TN.annotations_module=e4;g.TN.creatorendscreen=v3;})(_yt_player);
